services:
  busted-tests:
    #build: .
    image: ghcr.io/paliak/busted-tests
    environment:
      HOME: /tmp
    container_name: busted-tests
    user: nobody:nobody
    command: busted --lua=luajit
    security_opt:
      - no-new-privileges:true
    ports:
      - "9966:9966"
    working_dir: /workdir
    volumes:
      - ./:/workdir:ro
  busted-diff:
    #build: .
    image: ghcr.io/paliak/busted-tests
    environment: #Where in the container the folders are stored
      WORKDIR: /workdir
      HOME: /tmp
    container_name: busted-diff
    tty: true
    user: nobody:nobody
    command: /bin/sh -c "dos2unix < /workdir/spec/buildDiff.sh | /bin/sh"
    security_opt:
      - no-new-privileges:true
    working_dir: /workdir
    volumes:
      - ./:/workdir:ro
